version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk-browsers-legacy
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: cd credhub; git checkout d8a969690223661f44dd2fe4b48829a19f16e42c; cd - 
      - run: cd credhub-acceptance-tests; git checkout master; cd -
      - run: pwd; ls
      - run: ./prepare_build.sh
      - setup_remote_docker:
          version: 18.05.0-ce
      - run: docker build -t ampersand8/credhub .
      - run: docker login -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
      - run: docker push ampersand8/credhub
